### ISSUE TITLE
Host watch is not working if {hostpath} contain [space]

### ISSUE THREAD

**Issue by thuannguyenit** [mhallin/vagrant-notify-forwarder#20]
For example: Host path is "/var/www/project name/source code", then Host watch is not working when start "vagrant up"

**Comment by tremby** [comment]
Possibly related, I can't start the VM with this installed, and it appears to be due to a space in the path to the VM itself:

```
/Volumes/Macintosh HD Storage/.vagrant.d/gems/2.4.4/gems/vagrant-notify-forwarder-0.5.0/lib/vagrant-notify-forwarder/action/start_host_forwarder.rb:24:in `spawn': No such file or directory - /Volumes/Macintosh (Errno::ENOENT)
	from /Volumes/Macintosh HD Storage/.vagrant.d/gems/2.4.4/gems/vagrant-notify-forwarder-0.5.0/lib/vagrant-notify-forwarder/action/start_host_forwarder.rb:24:in `start_watcher'
```

**Comment by tremby** [comment]
I eventually got things working -- the issue was where VAGRANT_HOME was rather than where the VM was. I had VAGRANT_HOME pointing to something in `/Volumes/Macintosh HD Storage/...`. I believe not handling this correctly is a big in vagrant-notify-forwarded, but I'm not sure if it's the same as the OP.
